image: debian/bookworm
packages:
  - python3
  - python3-pip
  - python3-venv
  - cargo
sources:
  - https://git.sr.ht/~ruivieira/valis-core
tasks:
  - setup: |
      cd valis-core/valis_core
      cargo build
  - test: |
      cd valis-core/valis_core
      cargo test
